"""add scheme_id and entity_label to dependent_systems

Revision ID: 4e19f1d89d3c
Revises: 7a70095e2429
Create Date: 2026-07-08 04:27:28.642797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e19f1d89d3c'
down_revision: Union[str, Sequence[str], None] = '7a70095e2429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependent_systems', sa.Column('scheme_id', sa.String(), nullable=True))
    op.add_column('dependent_systems', sa.Column('entity_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dependent_systems', 'entity_label')
    op.drop_column('dependent_systems', 'scheme_id')
    # ### end Alembic commands ###
