"""add parsed_effective_date and rule_conflicts table

Revision ID: 579494dcf544
Revises: 4e19f1d89d3c
Create Date: 2026-07-08 05:33:11.562560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579494dcf544'
down_revision: Union[str, Sequence[str], None] = '4e19f1d89d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_conflicts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('rule_a_id', sa.String(), nullable=False),
    sa.Column('rule_b_id', sa.String(), nullable=False),
    sa.Column('governing_rule_id', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('resolution_reason', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("resolution IN ('a_governs', 'b_governs', 'ambiguous_missing_date', 'both_future')", name='valid_conflict_resolution'),
    sa.ForeignKeyConstraint(['governing_rule_id'], ['rule_deltas.id'], ),
    sa.ForeignKeyConstraint(['rule_a_id'], ['rule_deltas.id'], ),
    sa.ForeignKeyConstraint(['rule_b_id'], ['rule_deltas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rule_deltas', sa.Column('parsed_effective_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule_deltas', 'parsed_effective_date')
    op.drop_table('rule_conflicts')
    # ### end Alembic commands ###
