"""circular_id nullable for adhoc rule checks

Revision ID: 7a70095e2429
Revises: 807c6d03a7e6
Create Date: 2026-07-05 05:35:34.298071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a70095e2429'
down_revision: Union[str, Sequence[str], None] = '807c6d03a7e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rule_deltas', 'circular_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rule_deltas', 'circular_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
